// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvS1Rh_bo1JUVyQ82J8aymuWBYjlwbM6w',
    appId: '1:337720268596:android:e836b2c93422f5c3857761',
    messagingSenderId: '337720268596',
    projectId: 'health-plus-d1f74',
    storageBucket: 'health-plus-d1f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC95WEDiczja2mA9Fi-se0MN20IWKQRm_0',
    appId: '1:337720268596:ios:f6c166d351b6f38d857761',
    messagingSenderId: '337720268596',
    projectId: 'health-plus-d1f74',
    storageBucket: 'health-plus-d1f74.appspot.com',
    iosClientId: '337720268596-cc7eculb0e2qc0lqg3aqfj5rognnthrb.apps.googleusercontent.com',
    iosBundleId: 'com.syject.healthplus',
  );
}
